### ISSUE TITLE
After Effects Error: internal verification failure, sorry! {unexpected matchname searched for in group}  (29 :: 0)

### ISSUE THREAD

**Issue by Nico-Duduf** [Duduf-dev/Duik#75]
In my After Effects Comp I have a pre-comp of an 'arm'
I have given it puppet pin joints for and named them R_HAND, R_ELBOW and R_SHOULDER
I have given those puppet pin joints BONES (successfully)
I have made HAND_R the CONTROLLER (successfully)
I have 'parented' B_R_HAND to B_R_ELBOW and B_R_ELBOW to B_R_SHOULDER then selected the layers B_R_HAND then B_R_ELBOW then B_R_SHOULDER then C_B_R_HAND
I have clicked the 'IK' button
This brought up the "Options d'IK" pop up
I unticked "Controleurs de Stretch"
I clicked "OK"

This brings up a box with an error which reappears when the OK dismiss is clicked (therefore locking me out of AE).

Here's a screenshot of the error

http://www.jimlefevre.com/wp-content/uploads/2015/03/crash_01.jpg

But it reads....

After Effects Error: internal verification failure, sorry!{unexpected matchname ssearched for in group}

(29 :: 0)

**Comment by Nico-Duduf** [comment]
This is a bug from After Effects CC2014, can't do anything. Has been corrected with v2014.1.1

**Comment by jewelduan** [comment]
how to solve that bug? instead of updating my after effect?

**Comment by Nico-Duduf** [comment]
To my knowledge, this is impossible. You should update to CC2014.2 if you want to keep CC2014, or update to the latest CC2015.

**Comment by jewelduan** [comment]
Thanks a lot!

**Comment by chimichunga1** [comment]
Hi i know this thread is old but im still having some issues and im not sure if its with the duik or the after effects 

![screenshot 641](https://cloud.githubusercontent.com/assets/22383204/18770687/36a7b6f0-816b-11e6-9782-a13b72317394.png)

**Comment by Nico-Duduf** [comment]
Hi, I opened a new issue with your bug: #246
We'll have to find what's wrong.
Can you post on the new issue what is your version of After Effects and Windows, and what you were doing when this error was shown (creating a 2-layer IK?)

**Comment by eva-01** [comment]
Hi! I have the same issue, is there already a sollution?
Thanks!

**Comment by maladziewczynka** [comment]
HI! Nico-Duduf how did you solve your problem? I attach the attachment. 
Not only that I can not turn off the message. I can not turn off the program After Effect

![duik](https://cloud.githubusercontent.com/assets/24223341/20665787/3f5ed15a-b561-11e6-8975-dc8810cf7ce9.jpg)

**Comment by eva-01** [comment]
Hi maladziewczynka! The only way I found to solve the problem, was updating After Effects.

**Comment by maladziewczynka** [comment]
Thank you, not help:(
